language: node_js
node_js:
  - "node"
cache: yarn install
script:
  - yarn run lint
  - yarn run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
